eureka:
  client:
    serviceUrl:
      defaultZone: http://172.25.241.179:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost
    
internalRoutes:
    keyService:
        name: KEYS-SERVER
        routes:
            getMachineJobKeys: /api/machineJobKeys/
           
